Game.create(home_team: "Nebraska Cornhuskers", away_team: "Fresno State Bulldogs", date: "9-03")
Game.create(home_team: "Nebraska Cornhuskers", away_team: "Wyoming Cowboys", date: "9-10")
Game.create(home_team: "Nebraska Cornhuskers", away_team: "Oregon Ducks", date: "9-17")
Game.create(home_team: "Northwestern Wildcats", away_team: "Nebraska Cornhuskers", date: "9-24")
Game.create(home_team: "Nebraska Cornhuskers", away_team: "Illinois Fighting Illini", date: "10-1")
Game.create(home_team: "Indiana Hoosiers", away_team: "Nebraska Cornhuskers", date: "10-15")
Game.create(home_team: "Nebraska Cornhuskers", away_team: "Purdue Boilermakers", date: "10-22")
Game.create(home_team: "Wisconsin Badgers", away_team: "Nebraska Cornhuskers", date: "10-29")
Game.create(home_team: "Ohio State Buckeyes", away_team: "Nebraska Cornhuskers", date: "11-5")
Game.create(home_team: "Nebraska Cornhuskers", away_team: "Minnesota Gophers", date: "11-12")
Game.create(home_team: "Nebraska Cornhuskers", away_team: "Maryland Terrapins", date: "11-19")
Game.create(home_team: "Iowa Hawkeyes", away_team: "Nebraska Cornhuskers", date: "11-25")
